version: '3.9'  
services:
  keycloak_container:
    image: quay.io/keycloak/keycloak:20.0.0
    environment:
      DB_TYPE: postgres  
      DB_HOST: postgres_keycloak 
      DB_NAME: keycloak  
      DB_PASSWORD: password  
      DB_USER: keycloak  
      DB_SCHEMA: public  
      ADMIN_USER: admin  
      ADMIN_PASSWORD: admin  
      PROXY_MODE: edge  
      ADMIN_URL: http://localhost:8088 
      CLIENT_URL: http://localhost:8088 
    depends_on:
      - postgres_container   
    networks:
      - keycloak_nginx_network

  postgres_container:
    image: postgres:14.2
    volumes:
      - pgdata_keycloak_nginx:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    networks:
      - keycloak_nginx_network

  keycloak_nginx:
    image: nginx:alpine
    ports:
      - "8001:80"
    depends_on:
      - keycloak_container
    networks:
      - keycloak_nginx_network
    volumes: 
      - /home/testadmin/nginx.conf:/etc/nginx/nginx.conf #Bind  volume

volumes:
  pgdata_keycloak_nginx:
  

networks:
  keycloak_nginx_network: