name: Deploy Keycloak

on:
  push:
    branches:
      - feature/deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AZURE_VM_SSH_KEY }}  
    - name: Copy Docker Compose File
      run: |
        scp -o StrictHostKeyChecking=no ./ansible/docker-compose.yaml testadmin@20.224.56.187:/home/docker-compose.yaml
    - name: Copy Nginx Configuration File
      run: |
        scp -o StrictHostKeyChecking=no ./nginx.conf testadmin@20.224.56.187:/home/nginx.conf
    - name: Install Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no testadmin@20.224.56.187 'sudo apt-get update && sudo apt-get install -y docker-compose && sudo docker-compose down --volumes'
        ssh -o StrictHostKeyChecking=no testadmin@20.224.56.187 'docker-compose --version'

    - name: Run Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no testadmin@20.224.56.187 'cd /home/azureuser && sudo docker-compose up -d'
        docker ps 