name: Install Docker in Azure VM with Ansible

on:
  push:
    branches:
      - feature/configuration

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Add VM to Ansible inventory
        run: |
          echo "[azure_vm]" > inventory
          echo "13.93.82.114" >> inventory  

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i inventory ansible/docker_installation.yaml -u azureuser --private-key ~/.ssh/id_rsa -e 'ansible_ssh_common_args="-o StrictHostKeyChecking=no"'